version: "2"

services:
  app:
    build: .
    ports: "3000:3000"
    env_file: .env
    links:
      - db

  db:
    image: postgres:9.4
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

